modules/grafana/domain.tf
modules/grafana/load_balancer.tf
modules/grafana/service.tf

Previously we were creating an aws route53 record with a weighted policy however we were directing all of the traffic the same resource, a simple routing policy seemed more appropriate here

change route policy

---

.github/workflows/main.yml
main.tf

This enables us to check for invalid Terraform like an unsupported argument by running `terraform validate` which TFLint doesn't provide.
See [Terraform validate](https://www.terraform.io/docs/commands/validate.html).

Add validation of Terraform in CI/CD

---

variables.tf

This reverts commit 1668f2c5d1290a7462d084d662efbcbba3105126.

Revert "deleted some variables"

---

buildspec.yml
main.tf
modules/bsi_pentest_vm/main.tf
modules/bsi_pentest_vm/variables.tf
variables.tf

This is for deployment of a kali Linux ec2 instance requested by BSI to aid their penetration test

Bsi pen test vms

---

buildspec.yml
modules/grafana/iam.tf
modules/grafana/sns_subscription.tmpl
modules/grafana/sns_topic.tf
modules/monitoring_platform/policies.tf
modules/prometheus/iam.tf
modules/prometheus/service.tf

template_file has been depreciated, this PR replaces all usages of it with the function [templatefile](https://www.terraform.io/docs/language/functions/templatefile.html)

Replace usage of template_file 

---

Makefile

removes the clean target from the Makefile and adds specific aws-vault profile in the aws-vault clear so that it does not clear other sessions.

updates Makefile

---

buildspec.yml

adds -auto-approve correctly. it was done incorrectly last time.

terraform state replace-provider command fix

---

buildspec.yml
scripts/deploy_kubernetes.sh

install helm in buildspec and setting bash scrip to fail pipeline if unsuccessful and removed aws-vault from the command.

install helm in buildspec

---

Makefile
outputs.tf
scripts/deploy_kubernetes.sh

In order to run the Kubernetes deploy under aws-vault we need to
apply some special session handling. This will help  bake this
knowledge in the repo and make it easier for developers to deploy
kubernetes to dev environments
Co Authored with @paulmchenry

Add kubernetes deploy to Makefile

---

.env.example
Makefile
README.md
buildspec.yml
kubernetes/prometheus-thanos/values.yaml
main.tf
modules/prometheus/service.tf
modules/prometheus/variables.tf
mojo.tf
scripts/deploy_kubernetes.sh
variables.tf

thanos image has been pushed to it's own shared services base image repository. ecs task definitions and kubernetes deployment scripts to change to pull image from the new ecr repo.

pull thanos from ecr

---

buildspec.yml
main.tf
modules/grafana/service.tf
modules/grafana/variables.tf
mojo.tf
variables.tf

- updates grafana module to pull below images from the base images repo:
```
- grafana
- grafana-image-renderer
```
- adds new variables to pass the repository urls
- adds variables in Buildspecs

updates Grafana to pull images from base images repo

---

buildspec.yml
main.tf
modules/grafana/service.tf
modules/grafana/variables.tf
mojo.tf
variables.tf

- adds 'respository url' to the names

fixes variable names for Grafana images

---

kubernetes/prometheus-thanos/templates/thanos-store-deployment.yaml
modules/monitoring_platform/eks.tf
modules/monitoring_platform/policies/kms_access_policy.template.json
modules/monitoring_platform/variables.tf
mojo.tf

Adding in the files required to deploy Thanos store and the associated configuration.

Add Thanos Store Deployment

---

scripts/deploy_kubernetes.sh

We will remove this once it has run through the pipeline

Uninstall release with the old name

---

scripts/deploy_kubernetes.sh

Now that the old chart has been uninstalled we can remove this command.

Remove uninstall command

---

kubernetes/prometheus-thanos/templates/thanos-querier-deployment.yaml
kubernetes/prometheus-thanos/templates/thanos-querier-service.yaml
kubernetes/prometheus-thanos/templates/thanos-store-deployment.yaml
kubernetes/prometheus-thanos/templates/thanos-store-service.yaml

- Renamed the thanos store manifests to match the new naming style.
- Created a service manifest for thanos store and added it to thanos querier's list of store API's.
- Created a service manifest for thanos querier, with internal load balancing so that it can be connected to from within the VPC.

Kubernetes tweaks

---

.terraform.lock.hcl
modules/test_bastion/bastion.tf
modules/test_bastion/routing.tf
modules/test_bastion/security_groups.tf
modules/test_bastion/ssh.tf
modules/test_bastion/ssm.tf
modules/test_bastion/variables.tf
mojo.tf
variables.tf

deploys a bastion test VM for testing

Test bastion

---

variables.tf

set the variable to 'false' to terminate bastion test VM

Remove test Bastion

---

mojo.tf
mojo_outputs.tf

private subnets 
[
"10.180.100.0/25",
"10.180.101.0/25",
"10.180.102.0/25",
]
public subnets 
[
"10.180.100.128/25",
"10.180.101.128/25",
"10.180.102.128/25",
]

updates subnets cidr blocks using a cidrsubnets terraform function

---

README.md

- Make it clear that terraform should be installed via tfenv
- Update referenced terraform version to match what's being used now

Update getting started section in readme

---

buildspec.yml
mojo.tf
mojo_outputs.tf

after the previous infra has been destroyed, this re deploys the infra with updated subnets.

re-deploys infra with updated subnets

---

buildspec.yml

Adding this back in as ECR needs it.

Add thanos_image_repository_url back in.

---

.terraform.lock.hcl
Makefile

Adding this to the apply target to make sure our terraform outputs stay up to date when working in workspaces.

Publish terraform outputs when running make apply

---

modules/grafana/service.tf

Added some new visualization panels :
- [polystat](https://grafana.com/grafana/plugins/grafana-polystat-panel)
- [Status Panel](https://grafana.com/grafana/plugins/vonage-status-panel)
- [Flowcharting](https://grafana.com/grafana/plugins/agenty-flowcharting-panel/)
And an alertmanager datasource option.

Adding some plugins to Grafana to enrich new dashboards

---

main.tf
modules/monitoring_platform/network.tf
modules/monitoring_platform/variables.tf
modules/monitoring_platform/vpc_dhcp_options.tf
modules/test_bastion/security_groups.tf
variables.tf

adds a new DHCP option set
attaches the new option set to the VPC
adds two new routes in main route table
to route DNS traffic through the TGW

changes VPC DNS to MoJO DNS servers

---

modules/monitoring_platform/logging.tf
modules/monitoring_platform/network.tf

creats an IAM role for flow logging
and creates flow log in cloudwatch

changes flow log destination to cloudwatch

---

modules/grafana/service.tf

switching from user 104 to 472 and also adding group ID to ecs task definition parameters

:construction: update user id and add group id

---

modules/blackbox_exporter/security_groups.tf
modules/snmp_exporter/security_groups.tf

Reverts ministryofjustice/staff-infrastructure-monitoring#137

:rewind: ":passport_control: allowing public and private subnets to blackbox and SNMP"

---

main.tf

eks feature flag

---

.terraform.lock.hcl
main.tf
s3-buckets.tf

Reverts ministryofjustice/staff-infrastructure-monitoring#167

Revert ":recycle: Refactor aws.env in modules"

---

.terraform.lock.hcl
modules/s3_bucket/main.tf
modules/s3_bucket/variables.tf
s3-buckets.tf

:recycle: refactor s3 bucket logging

---

modules/s3_bucket/main.tf
s3-buckets.tf

Disabling encryption on s3 bucket in order to try and re-encrypt with the new KMS key

:bug: disable encryption on thanos s3 bucket

---

modules/s3_bucket/main.tf
s3-buckets.tf

Reverts ministryofjustice/staff-infrastructure-monitoring#178

Revert ":bug: disable encryption on thanos s3 bucket"

---

modules/grafana/service.tf

apply the latest version to fix reported vulnerabilities.

:ambulance: update grafana to latest version

---

buildspec.yml
main.tf
variables.tf

Values are in shared services param store

:recycle: add a feature flag for EKS cluster and remove EKS from dev and pre-prod

---

Makefile
README.md
scripts/generate_tfvars.sh

Add generate tfvars file to speed up local development

:robot: automate pulling the tfvars down from aws

---

buildspec.yml

Turn off transit gateway
