ministryofjustice/staff-infrastructure-monitoring

modules/grafana/external_image_storage.tf
modules/grafana/iam.tf
modules/grafana/policies/s3_access_policy.template.json
modules/grafana/service.tf

This PR enables Grafana to render images using Grafana Image Renderer as a remote HTTP rendering service i.e. another container sitting beside it in the Fargate task. We then use AWS S3 to store the rendered image for usage when sending alert notifications.

Add image rendering and external image storage for Grafana

---

.github/workflows/main.yml
scripts/lint_terraform.sh

Currently in this repo to lint Terraform files in CI, we've hardcoded the directories required. This nicks the script that finds `.tf` files and lints them we have in our config repo and uses in this repo.

Update Terraform linting to use script from config repository

---

buildspec.yml
scripts/Gemfile
scripts/Gemfile.lock
scripts/create_ci_user.rb

This script creates a user in Grafana for the configuration pipeline to use.  Eliminating the need to use the admin account to perform CI changes.

Ci user script

---

modules/grafana/load_balancer.tf
modules/grafana/security_groups.tf

- Added an ALB listener that redirects traffic from HTTP to HTTPS for grafana
- Added a security group rule to allow HTTP traffic into the ALB so it can redirect to HTTPS

Redirect http to https

---

README.md

I've added the example `terraform.tfvars` file to parameter store, with some values that are the same across accounts, pre-populated.

Update README to direct people to SSM for the terraform.tfvars file

---

main.tf
modules/prometheus/service.tf
modules/prometheus/variables.tf
mojo.tf

Adds [thanos compactor](https://github.com/thanos-io/thanos/blob/main/docs/components/compact.md) to our ECS cluster. This ensures that long term metric data is stored efficiently in s3.

Thanos compactor

---

buildspec.yml
scripts/authenticate_docker.sh
test/docker-compose.yml
test/run_test.sh

Changed run_test script to grep from the beginning of the line, as I often have dev & my workspace vars, with one commented out.

Pull selenium image from aws ecr repository in shared services account

---

modules/monitoring_platform/network.tf

Ticket [PTTP-2885](https://dsdmoj.atlassian.net/browse/PTTP-2885)
When specifying the [terraform default security group](https://dsdmoj.atlassian.net/browse/PTTP-2885) in terraform, be default on inbound or outbound rules will be created. So bringing this under terraforms control should close the default security group to all traffic.

Define the default security group in terraform

---

modules/blackbox_exporter/security_groups.tf

Restricting access to the blackbox exporter to only the private subnet that prometheus is on.

Updating security group to use private subnet CIDR block.

---

modules/monitoring_platform/eks.tf

The EKS terraform module appears to have some bugs relating to the AWS auth against the cluster. We can avoid these issues by manually generating our auth roles.

Manage auth for the EKS cluster manually

---

modules/blackbox_exporter/security_groups.tf
modules/prometheus/security_groups.tf
modules/snmp_exporter/security_groups.tf

Updating the CIDR block values in the security groups specified to restrict inbound access to only IPs in the private subnets being used.
------------------------------------------------------------------------
```sh
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the following actions:
~ resource "aws_security_group" "lb_blackbox_exporter" {
arn                    = "arn:aws:ec2:eu-west-2:068084030754:security-group/sg-08fce1e0bd003a118"
description            = "controls access to the ALB"
egress                 = [
{
cidr_blocks      = [
"0.0.0.0/0",
]
description      = ""
from_port        = 0
ipv6_cidr_blocks = []
prefix_list_ids  = []
protocol         = "-1"
security_groups …
```

Updating CIDR Blocks in Security Groups

---

modules/monitoring_platform/eks.tf
modules/monitoring_platform/outputs.tf
mojo_outputs.tf

- Upgrade version of eks module - a minimum of 1.16 is required for prom helm charts
- enable private access to the cluster
- enable logging of the cluster to cloudwatch
- output the role arn as this is needed to manually create a config map

A few cluster updates

---

buildspec.yml

Since the terraform upgrade from 0.12.x to 0.13.x some providers sources need to be manually replaced on the remote state file.
more information: https://www.terraform.io/upgrade-guides/0-13.html#why-do-i-see-provider-during-init-

replace-provider on terraform remote state

---

modules/grafana/service.tf

When spinning up new environments we are running into issues when using the new 1.4.0 version. So specifying 1.3.0 here to ensure that version is used.

Explicitly specific which version of Fargate to use

---

buildspec.yml

terraform state replace-provider commands were temporarily needed to help with the terraform upgrade from 0.12.x to major version 0.13.x. 
Since, Terraform is now upgraded to 0.13.x, those replace-provider commands are removed.

removes terraform state replace-provider commands

---

kubernetes/prometheus-thanos/templates/thanos-compactor-deployment.yaml
kubernetes/prometheus-thanos/values.yaml
modules/monitoring_platform/eks.tf
modules/monitoring_platform/policies/s3_access_policy.template.json
modules/monitoring_platform/variables.tf
mojo.tf

adds conditional deployment for the compactor container
also adds s3 access policy to the worker iam role
Notes:
we have set the flag to deploy compactor to `false` so that two instances of thanos compactor do not write to the same s3 bucket at the same time.

adds deployment of thanos compactor to kubernets

---

modules/monitoring_platform/eks.tf

Upgrading the version of the EKS module for 10.0.0 -> 14.0.0, will subsequently increase the kubernetes versions.
The default root volume type is "gp3", here I have overridden this default as it was throwing an error when running in my workspace.

PTTP-3251/upgrade kubernetes version

---

kubernetes/prometheus-thanos/templates/prometheus-ingress.yaml

The API version `extensions/v1beta1` has is being deprecated, replacing here with the API `networking.k8s.io/v1`

Replace deprecated API

---

modules/monitoring_platform/eks.tf

When creating the eks module, we thought that setting `manage_aws_auth=false` meant we would have to create our own IAM role for the cluster.
It actually means that we have to manually upload the auth config map, which we manage in helm. 
The role we created here isn't being used by anything.

The cluster role we created isn't used in the eks module

---

scripts/migrate-db.sh
scripts/pause_alerts.sh

- Added a new bash script to pause all the alerts for grafana
- Changed the migrate db script to
1, delete the current database that's sitting in the new VPC
2, Create a snapshot of the database sitting in the old VPC
3, recreate the database sitting in the new VPC from this snapshot
4, delete the snapshot that was just created
This should make it quicker to switch over the databases when we need to. 
FYI - when doing this, grafana in the new VPC will take on the configuration of the one in the old VPC which will cause it to fire off alerts as the Prometheus URL in data sources will be the wrong one.

Pause alerts script + flesh out migrate db script

---

.github/workflows/main.yml
.terraform.lock.hcl
buildspec.yml
database/.terraform.lock.hcl
database/versions.tf
scripts/deploy_kubernetes.sh
versions.tf

Upgrades terraform from 0.13 -> 0.14 
updates the deploy kubernetes script to remove double quotes from string values it uses from terraform outputs

Upgrade terraform

---

main.tf

The development build is failing due to this missing value. This was overlooked previously due to the resources in main.tf being commented out during development.

Adding storage key ARN to monitoring platform module.

---

kubernetes/prometheus-thanos/templates/alertmanager-configmap.yaml
kubernetes/prometheus-thanos/templates/alertmanager-deployment.yaml
kubernetes/prometheus-thanos/templates/alertmanager-service.yaml
kubernetes/prometheus-thanos/templates/prometheus-deployment.yaml
kubernetes/prometheus-thanos/templates/prometheus-ingress.yaml
kubernetes/prometheus-thanos/templates/thanos-compactor-deployment.yaml
kubernetes/prometheus-thanos/templates/thanos-querier-deployment.yaml
kubernetes/prometheus-thanos/templates/thanos-receiver-deployment.yaml
kubernetes/prometheus-thanos/templates/thanos-receiver-service.yaml
scripts/deploy_kubernetes.sh

Added a service and deployment for alertmanager. The configuration for alertmanager is held in a configmap which we mount onto the pod.
We haven't configured any "notification channels" as this was out of scope for the ticket but have tested that when an alert goes off in prometheus we can view it in the alert manager UI, by using port forwarding.
also some tidy up...
- updates names in all templates to include `ReleaseName` in pods names
- removes `deployment` word from pods names

Pttp 3735/deploy alertmanager in kubernetes

---

main.tf
modules/blackbox_exporter/load_balancer.tf
modules/blackbox_exporter/variables.tf
modules/grafana/load_balancer.tf
modules/grafana/variables.tf
modules/prometheus/load_balancer.tf
modules/prometheus/variables.tf
modules/s3_bucket/main.tf
modules/s3_bucket/variables.tf
modules/snmp_exporter/load_balancer.tf
modules/snmp_exporter/variables.tf
mojo.tf

This change enables ELB_v2 access logging on the load balancers to an AWS S3 bucket for Grafana, Prometheus, Blackbox_Exporter and SNMP_Exporter as per pen test recommendations. 
Jira - [PTTP-3589](https://dsdmoj.atlassian.net/browse/PTTP-3589)

PTTP-3589 Enable ELBv2 access logging to AWS S3

---

modules/blackbox_exporter/load_balancer.tf

corrects the prefix name in the AWS S3 bucket for the blackbox_exporter load balancer access logs.

Corrects prefix name for BB S3 bucket

---

main.tf

After this PR I will open a new one to assign `monitoring-alerting.staff.service.justice.gov.uk` to the new mojo infra

adding '-decomissioned' to the domain prefix to free up the current A record

---

kubernetes/prometheus-thanos/templates/azure-metrics-exporter-service.yaml
kubernetes/prometheus-thanos/templates/azure-metrics-exporter.yaml

also creates a service for the pod containing azure metrics exporter
this deployment depends on the configmaps that are created by:
https://github.com/ministryofjustice/staff-infrastructure-metric-aggregation-server/tree/spike-pushing-config-maps

deploys Azure metrics exporter container in EKS cluster

---

buildspec.yml
modules/blackbox_exporter/variables.tf
modules/cloudwatch_exporter/iam.tf
modules/cloudwatch_exporter/outputs.tf
modules/cloudwatch_exporter/policies/cloudwatch_access_policy.template.json
modules/cloudwatch_exporter/variables.tf
modules/grafana/variables.tf
modules/monitoring_platform/eks.tf
modules/monitoring_platform/eks_policies.tf
modules/monitoring_platform/outputs.tf
modules/monitoring_platform/policies/cloudwatch_access_policy.template.json
modules/monitoring_platform/variables.tf
modules/prometheus/variables.tf
modules/snmp_exporter/variables.tf
mojo.tf
mojo_outputs.tf
variables.tf

This adds an alertmanager instance to the EKS cluster with a few initial metrics, with metrics being retrieved for their respective accounts for dev and pre-production but in production retrieving metrics from dev, pre-production and production.
- Adds a policy to give access to cloudwatch for the worker nodes, I refactored all the policies into a separate file whilst doing this. 
- Creates roles for production account to assume that allow it to get metrics in the other accounts
We will flesh out the production config file for the exporter in a later PR.

Pttp 3736/cloudwatch exporter

---

modules/grafana/outputs.tf
outputs.tf

Prometheus alertmanager configmap will use this `SES email from` to
configure the alerts to send email notifications.

adds `AWS SES Email From` in `Terraform outputs`

---

modules/monitoring_platform/policies/s3_access_policy.template.json

This was adding "arn:aws:s3:::" as a prefix to the bucket name when this was already being included as part of the bucket name.

Fixing problem with S3 bucket ARN address.

---

modules/cloudwatch_exporter/policies/cloudwatch_access_policy.template.json
modules/monitoring_platform/policies/cloudwatch_access_policy.template.json

As per the [yace docs](https://github.com/ivx/yet-another-cloudwatch-exporter/blob/master/README.md#iam) cloudwatch exporter needs this permission to discover API gateway resources.

Give cloudwatch exporter permission to discover api gateway resources

---

buildspec.yml
main.tf
modules/monitoring_platform/network.tf
modules/monitoring_platform/route53_resolver.tf
modules/monitoring_platform/security_group.tf
modules/monitoring_platform/variables.tf
variables.tf

and create mojo dns route 53 rules to forward dns queries to mojo dns for gsi domain.
this feature is only enabled in production environment.
a flag is used to filter non production environments.

Create an outbound Route53 endpoint

---

modules/grafana/service.tf

Removing specified version number for ECS so it will use the latest version by default

Removing specified version number for ECS

---

modules/blackbox_exporter/security_groups.tf
modules/snmp_exporter/security_groups.tf

Allowing public and private VPC IPs to access the Blackbox and SNMP exporters until the EKS cluster is rebuilt with stricter IP settings.

:passport_control: allowing public and private subnets to blackbox and SNMP

---

modules/monitoring_platform/eks.tf

User Story:
As CloudOps engineers 
I want to be on a more current version of EKS
So that we don’t fall behind on versions, as AWS will stop the support of older versions at some point.
Value / Purpose  
This will identify any deprecations that may affect code and deployments. This will also make us better prepared of dependencies that may arise.
Useful Contacts
CloudOps Team

:wrench:PTTP-8592-Upgrade-EKS-1.19to1.20

---

modules/monitoring_platform/eks.tf

This change follows [this](https://github.com/ministryofjustice/staff-infrastructure-monitoring/commit/d61ede47813c3aa139aa22ef3db5237710f11df0) commit, and upgrades the running EKS version from 1.20 to 1.21.

:wrench: Update EKS Cluster to v1.21

---

main.tf

This PR will update the monitoring_platform and prometheus modules with the new Thanos s3 bucket.  This will correct missing permissions and allow pods in EKS to interact with the new bucket.

:truck: point modules to new Thanos s3 bucket

---

main.tf
modules/monitoring_platform/certificates.tf
modules/monitoring_platform/outputs.tf
modules/monitoring_platform/variables.tf
outputs.tf

This PR has been raised in relation to this issue: ministryofjustice/staff-infrastructure-monitoring-deployments#78 
This configuration seeks to add a certificate which will be used in conjunction with an nginx proxy to pass ALZ traffic to the IMA platform.

:sparkles: Add thanos receiver certificate Config

---

modules/monitoring_platform/certificates.tf

`thanos-secure-development.dev.staff.service.justice.gov.uk` will now appear as `thanos-secure.dev.staff.service.justice.gov.uk` thereby removing the double mention of development.

:pencil2: Edit thanos_receiver cert name

---

modules/monitoring_platform/policies/route_53_access.template.json

As part of the [Thanos over https Issue](https://github.com/ministryofjustice/staff-infrastructure-monitoring-deployments/issues/78)  we are deploying [cert-manager](https://cert-manager.io/docs/).  In order to resolve successful DNS challenges for new certificates, the cluster will need this additional permission within route53.

:wrench: Add GetChange to route53 IAM policy

---

modules/grafana/security_groups.tf

The purpose of this PR is to change the ingress ports used in the `lb_grafana` security group. 
At the moment the entire range from port 443 to 3000 is open in the security group. 
This PR seeks to resolve this by creating another ingress module (right terminology?) in `security_groups.tf` which opens up port 3000 and refactoring the original egress module (?) to open port 443. 
TLDR: (Range 443 up to and including 3000) -> (port 443 + 3000)

:wrench: Update grafana-lb ingress ports

---

modules/grafana/security_groups.tf

As per Trusted Advisor recommendation in [this](https://github.com/ministryofjustice/staff-infrastructure-monitoring/issues/173) ticket, this PR locks down the range from 0.0.0.0/0 to the relevant VPC CIDR block.

:lock: Locking down DB access to only VPC CIDR block

---

buildspec.yml
main.tf
modules/monitoring_platform/network.tf
modules/monitoring_platform/variables.tf
variables.tf

This PR will add IPs from the BYOIP pool to the IMA VPC NAT gateway.  This will allow Prometheus and co to scrape internal MoJ resources,

:bricks: add byoip to nat gateways
